#! /bin/bash

n="$h/$(awk -F\" '/name/{print $4}' package.json)"

h="https://blackwinter.de/addons"
a=( ${h//\// } )
u=${1:-$USER}

sed -i '/test-bookmarks/s:^/*://:' lib/main.js

cfx test &&\
cfx xpi --update-link "$h/$n.xpi" --update-url "$h/$n.update.rdf" &&\
scp keyword-expansion.* "$u@${a[*]:1:1}:/var/www/$(IFS=/; echo "${a[*]:2}")" &&\
rm keyword-expansion.*
